def draw_park():
    print("             |||               _____    ")
    print("           (  0   )           (^ o ^)")
    print("         (          )       // (   )\\  ")
    print("        (            )          ^^ ")
    print("      (               )                              ")
    print("      (     0           )                          ")
    print("     (             0     )        |________________|                ")
    print("   (                      )       |                |")
    print(" (  0                      )      |     chair      |                ")
    print("  (                         )     |                | ")
    print(" (                0         )    |__________________|")
    print(" (                         )     ||||||||||||||||||||")
    print("  (                    )         ||||||||||||||||||||                     ")
    print("   VVVVVVVVVVVVVVVVVVVVVVV                             ")
    print("           /||||\                    o                 ")
    print("          /||||| \                  / \                  ")
    print("         /||||||||\              ccccccco               ")
    print("        /||||||||||\             ( ^ c ^ )              ")
    print("       /||||||||||||\             (||:||)             ")
    print("      /||||||||||||||\             || ||              ")
    print("                                  (_) (_)  ")
    print(" ___     ___ ")
    print("(o o)   (o o)")
    print("(  V  ) (  V  ) ")
    print("/--m-m- /--m-m-")


    return
